[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
build_flags = -O2

lib_deps =
    m5stack/M5Unified
    m5stack/M5GFX
    meganetaaan/m5stack-avatar
    bblanchon/ArduinoJson